import { Property, Testimonial } from '@/types'

export const FEATURED_PROPERTIES: Property[] = [
  {
    id: '1',
    slug: 'penthouse-alto-noa-salta',
    title: 'Penthouse Alto NOA',
    short_description: 'Vista panorámica 360° sobre el valle de Lerma. Acabados de primera línea con tecnología domótica integrada.',
    type: 'venta',
    category: 'penthouse',
    status: 'disponible',
    price: 580000,
    currency: 'USD',
    surface_total: 310,
    surface_covered: 280,
    bedrooms: 4,
    bathrooms: 4,
    parking_spaces: 3,
    floor: 22,
    total_floors: 24,
    address: 'Av. Virrey Toledo 400',
    neighborhood: 'Centro',
    city: 'Salta',
    province: 'Salta',
    lat: -24.7884,
    lng: -65.4117,
    images: [
      'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=1200&q=80',
      'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=1200&q=80',
    ],
    cover_image: 'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=1200&q=80',
    amenities: ['Piscina privada', 'Terraza', 'Domótica', 'SUM', 'Gym', 'Cochera cubierta'],
    featured: true,
    highlight_label: 'EXCLUSIVO',
    created_at: '2024-01-15T10:00:00Z',
    updated_at: '2024-01-15T10:00:00Z',
  },
  {
    id: '2',
    slug: 'oficinas-premium-salta-centro',
    title: 'Torre Lerma Offices',
    short_description: 'Planta libre en el corazón del centro salteño. Ideal para headquarters corporativo o inversión de renta.',
    type: 'venta',
    category: 'oficina',
    status: 'disponible',
    price: 285000,
    currency: 'USD',
    surface_total: 320,
    surface_covered: 320,
    parking_spaces: 4,
    floor: 6,
    total_floors: 12,
    address: 'Av. Belgrano 540',
    neighborhood: 'Centro',
    city: 'Salta',
    province: 'Salta',
    lat: -24.7859,
    lng: -65.4116,
    images: [
      'https://images.unsplash.com/photo-1497366216548-37526070297c?w=1200&q=80',
      'https://images.unsplash.com/photo-1497366754035-f200581ddef8?w=1200&q=80',
    ],
    cover_image: 'https://images.unsplash.com/photo-1497366216548-37526070297c?w=1200&q=80',
    amenities: ['Planta libre', 'Doble altura', 'Parking', 'Seguridad 24h', 'Generador'],
    featured: true,
    highlight_label: 'CORPORATIVO',
    created_at: '2024-01-20T10:00:00Z',
    updated_at: '2024-01-20T10:00:00Z',
  },
  {
    id: '3',
    slug: 'casa-country-san-lorenzo',
    title: 'Residencia San Lorenzo',
    short_description: 'Arquitectura contemporánea en entorno privilegiado. 5000 m² de terreno con jardín diseñado y acceso directo a la serrania.',
    type: 'venta',
    category: 'residencial',
    status: 'disponible',
    price: 340000,
    currency: 'USD',
    surface_total: 520,
    surface_covered: 380,
    bedrooms: 5,
    bathrooms: 5,
    parking_spaces: 4,
    address: 'San Lorenzo Country Club',
    neighborhood: 'San Lorenzo',
    city: 'San Lorenzo',
    province: 'Salta',
    lat: -24.9083,
    lng: -65.4917,
    images: [
      'https://images.unsplash.com/photo-1613977257363-707ba9348227?w=1200&q=80',
      'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=1200&q=80',
    ],
    cover_image: 'https://images.unsplash.com/photo-1613977257363-707ba9348227?w=1200&q=80',
    amenities: ['Piscina', 'Jardín diseñado', 'Quincho', 'Estudio', 'Guest house'],
    featured: true,
    highlight_label: 'PREMIUM',
    created_at: '2024-02-01T10:00:00Z',
    updated_at: '2024-02-01T10:00:00Z',
  },
]

export const TESTIMONIALS: Testimonial[] = [
  {
    id: '1',
    name: 'Martín Aguirre',
    role: 'Director',
    company: 'Grupo Aguirre Inversiones',
    content: 'RADIX entiende el mercado de una manera que pocas firmas locales logran. Su capacidad de análisis y la calidad de los activos que manejan los posiciona en otro nivel. Tercera operación con ellos y la experiencia mejora cada vez.',
    rating: 5,
  },
  {
    id: '2',
    name: 'Valentina Roca',
    role: 'CEO',
    company: 'Roca & Partners',
    content: 'Buscábamos una sede en Salta que representara nuestra identidad corporativa. RADIX identificó opciones que nosotros nunca hubiéramos encontrado solos, y acompañó todo el proceso con una precisión extraordinaria.',
    rating: 5,
  },
  {
    id: '3',
    name: 'Federico Zabaleta',
    role: 'Inversor privado',
    company: '',
    content: 'Llevo cuatro años invirtiendo en real estate en Salta y Jujuy. Desde que trabajo con RADIX mis retornos mejoraron notablemente. Su conocimiento del mercado regional no tiene comparación.',
    rating: 5,
  },
]

export const INVESTMENT_STATS = [
  { value: '+240', label: 'Operaciones concretadas', suffix: '' },
  { value: '12', label: 'Años de trayectoria', suffix: '+' },
  { value: '180', label: 'En activos gestionados', prefix: 'USD ', suffix: 'M' },
  { value: '96', label: 'Clientes que vuelven', suffix: '%' },
]
